#!/bin/bash -e

# Include the `antd` component style dependencies to our context
# And solve an issue with `meteor-scss` that unable us to import css files
# by renaming the file as scss
# https://github.com/fourseven/meteor-scss/issues/219#issue-174566005
antdDeps=( "carousel" )
for antDep in ${antdDeps[@]}
do
  echo "Importing $antDep style dependency..."
  cp node_modules/antd/lib/$antDep/style/index.css imports/utilities/antd
  mv imports/utilities/antd/index.css imports/utilities/antd/_$antDep.scss
done

# Include the `prism` style dependency to our context
echo "Importing prism style dependency..."
cp node_modules/prismjs/themes/prism.css imports/utilities
mv imports/utilities/prism.css imports/utilities/_prism.scss
